### PR TITLE
change the img_path variable value

### LINKED ISSUE #3: product image and store logo not showing in linux
Hello, this project is interesting and I want to contribute to it.
- The first issue that I face when I run the project on my Linux machine is that the store logo and the product image are not showing! please see the screenshots attached! 
- I read the contribution guidelines that you offer and I will send a PR for the solution that I find!
screenshot_1_product_image
screenshot_2_logo_image
Thank you

### PR DESCRIPTION
**Pull request by medChaabi**
Fixes #3 
- I think that the problem comes from the img_path variable that exists on pos.js especially because of the app.getPath("appData")
Screenshot from 2024-07-06 17-56-06
- which gives us a wrong image/logo path 
screenshot_3_product_image_path
- I think that we can resolve this for now in the development environment by just changing the value of img_path from app.getPath('appData') to process.env.APPDATA
Screenshot from 2024-07-06 17-54-28
Screenshot from 2024-07-06 17-54-39

### I try to keep PRs small so I can understand the project better also if there is any info you can provide me with I will be grateful as I am still a beginner in the open-source world!

### CODE REVIEW

**Comment by Ayuen-madyt** [comment]
Thank Mohamed for your interest in contributing. i really appreciate.  I'll
merge your pull request tomorrow because right now its late

**Comment by Ayuen-madyt** [comment]
This a good step but i think using APPDATA will give issue with different operating systems. you could use path module which will solve the problem on different operating systems:

`const path = require('path');`
`
let img_path = path.join(app.getPath("appData"), "POS", "uploads");
`

**Comment by medChaabi** [comment]
Yes, I tried using app.getPath, and I still get the wrong image path! 
The problem is that we still use `process.env.APPDATA` on the API files folder (when we want to save an image or .db files).
so saving data with `process.env.APPDATA` and getting data with `app.getPath("appData")` do not generate the same path.
#### My solution is:
-  standardize all paths to the same value `process.env.APPDATA` and next, we give this variable the value that we want using `app.getPath("appData")` at the start of our application like this: 
 `process.env.APPDATA = path.join(app.getPath("appData"),...`
so that we can easily change it later if there is a problem and keep the paths matching.

**Comment by Ayuen-madyt** [comment]
> Yes, I tried using app.getPath, and I still get the wrong image path! The problem is that we still use `process.env.APPDATA` on the API files folder (when we want to save an image or .db files). so saving data with `process.env.APPDATA` and getting data with `app.getPath("appData")` do not generate the same path.
> 
> #### My solution is:
> * standardize all paths to the same value `process.env.APPDATA` and next, we give this variable the value that we want using `app.getPath("appData")` at the start of our application like this:
>   `process.env.APPDATA = path.join(app.getPath("appData"),...`
>   so that we can easily change it later if there is a problem and keep the paths matching.

I have actually tested your proposal on both mac and windows and `process.env.APPDATA` works on both.  thanks for pointing that out. much appreciated

**Pull request merged**
